version: "2"

services:
  api_service:
    build: ./demo
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - authorization-database
      - authorization-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.4:5432/projectsapi
      - SPRING_DATASOURCE_USERNAME=itk
      - SPRING_DATASOURCE_PASSWORD=itk2022
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      authorization-network:
        ipv4_address: 10.5.0.7

  authorization-server:
    container_name: authorization-server
    build:
      context: ./authorization-server
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - authorization-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.4:5432/authorization-db
    networks:
      authorization-network:
        ipv4_address: 10.5.0.6

  client-server:
    container_name: client-server
    build:
      context: ./client-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - resource-server
      - authorization-database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://10.5.0.4:5432/authorization-db
    networks:
      authorization-network:
        ipv4_address: 10.5.0.5
  
  authorization-database:
    container_name: authorization-database
    image: postgres
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=projectsapi, authorization-db
      - POSTGRES_USER=itk 
      - POSTGRES_PASSWORD=itk2022
    networks:
      authorization-network:
        ipv4_address: 10.5.0.4
    build: ./db 
    
networks:
  authorization-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1