version: "3.7"
services:
  api_service:
    build: ./demo
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - db
  db:
    build: ./db
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=projectsapi
