version: "3.7"
services:
  api_service:
    build: ./demo
    restart: always
    ports:
      - 8090:8090
    depends_on:
      - db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/projectsapi
    - SPRING_DATASOURCE_USERNAME=itk
    - SPRING_DATASOURCE_PASSWORD=itk2022
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    build: ./db
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_MULTIPLE_DATABASES=projectsapi, authorization-db
      - POSTGRES_USER=itk 
      - POSTGRES_PASSWORD=itk2022
